apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - name: app-frontend
        image: docker.io/husseinhaitham/app-frontend-mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  type: NodePort
  selector:
    app: app-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 30100
