apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-config-map
  namespace: default
data:
  mongo-url: mongo-service
  mongo-url-with-auth: mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-service:27017/hussdb?authSource=admin
