apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.labels.app }}
  labels:
    app: {{ .Values.frontend.labels.app }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.labels.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.labels.app }}
        image: {{ .Values.frontend.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }} 