apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  selector:
    app: {{ .Values.frontend.labels.app }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
  type: ClusterIP 