apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: {{ .Values.mongodb.labels.app }}
  ports:
  - port: {{ .Values.mongodb.service.port }}
    targetPort: {{ .Values.mongodb.service.targetPort }}
    protocol: TCP 