apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.labels.app }}
  labels:
    app: {{ .Values.backend.labels.app }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.labels.app }}
    spec:
      containers:
      - name: {{ .Values.backend.labels.app }}
        image: {{ .Values.backend.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        env:
        - name: MONGO_URI
          value: {{ .Values.backend.env.MONGO_URI }} 