apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    {{.Values.backend.ingress.annotations }}
   
spec:
  ingressClassName: {{ .Values.backend.ingress.className }}
  rules:
  - host: {{ .Values.backend.ingress.host }}
    http:
      paths:
      - path: {{ .Values.backend.ingress.path }}
        pathType: {{ .Values.backend.ingress.pathType }}
        backend:
          service:
            name: app-backend-service
            port:
              number: {{ .Values.backend.service.port }}
