apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
spec:
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP 